#!/usr/bin/env bash

while read oldrev newrev ref
do
    if [[ $ref =~ .*/(main|master)$ ]];
    then
        TARGET=$(mktemp -d)
        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f
        cd $TARGET
        if [[ -f ".deploy" ]]; then
          echo "Deploying Now!!"
          make -f .deploy
        else
          rm -rf $TARGET
          echo "Nothing To Deploy"
        fi
    else
        echo "Ref $ref received. Doing nothing: only the main or master branches may be deployed on this server."
    fi
done